global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Sample application metrics
  - job_name: 'sample-app'
    static_configs:
      - targets: ['sample-app:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules for alerting
rule_files:
  - "alert_rules.yml"
